version: '3.4'

services:
  vendingmachine-api:
    image: vendingmachine-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__VendingDatabase: "Server=vending-database;Initial Catalog=VendingMachine;User Id=SA;Password=ChangeIt123"
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - vending-database

  vending-database:
    image: mcr.microsoft.com/mssql/server
    ports:
     - 1434:1433
    environment:
     SA_PASSWORD: "ChangeIt123"
     ACCEPT_EULA: "Y"
    volumes:
     - sqldata:/var/opt/mssql

volumes:
  sqldata: