version: '3.4'

services:
  vendingmachine-api-unittests:
    image: vendingmachine-api-unittests
    build:
      context: .
      dockerfile: src/Api/Dockerfile
      target: testing
    environment:
      ConnectionStrings__VendingDatabase: "Server=vending-database;Initial Catalog=VendingMachine;User Id=SA;Password=ChangeIt123"
    entrypoint:
      - dotnet
      - test
      - /sln/test/Api.UnitTests/Api.UnitTests.csproj
      - -l
      - trx;LogFileName=/TestResults/api-unittests.xml
    volumes:
      - /TestResults://TestResults

  vendingmachine-api-integrationtests:
    image: vendingmachine-api-integrationtests
    build:
      context: .
      dockerfile: src/Api/Dockerfile
      target: testing
    environment:
      ConnectionStrings__VendingDatabase: "Server=vending-database;Initial Catalog=VendingMachine;User Id=SA;Password=ChangeIt123"
    entrypoint:
      - dotnet
      - test
      - /sln/test/Api.IntegrationTests/Api.IntegrationTests.csproj
      - -l
      - trx;LogFileName=/TestResults/api-integrationtests.xml
    volumes:
      - /TestResults://TestResults

  vending-database:
    image: mcr.microsoft.com/mssql/server
    ports:
     - 1434:1433
    environment:
     SA_PASSWORD: "ChangeIt123"
     ACCEPT_EULA: "Y"
    volumes:
     - sqldata:/var/opt/mssql

volumes:
  sqldata: